# version: '3'
services:
  chatgpt-on-wechat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatgpt-on-wechat
    volumes:
      - ./config.json:/app/config.json
      - ./plugins:/app/plugins
      - ./logs:/app/logs
    environment:
      TZ: Asia/Shanghai
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"